version: '3'

services:
  flask_app:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always

  prometheus:
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - flask_app

  grafana:
    build: 
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always  
    depends_on:
      - prometheus

volumes:
  grafana_data:
  prometheus_data:
