version: '3'

services:
  flask_app:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  prometheus:
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - flask_app

  grafana:
    build: 
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

